development:
  adapter: postgresql
  database: wedding-database-development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: wedding-database-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: wedding-database-production
  pool: 5
  timeout: 5000
